# Generated by Django 4.2.5 on 2024-05-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcshop', '0003_custom_notebooks_optimal_powerful'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcshop.categories', verbose_name='Категория'),
        ),
    ]
